### ISSUE TITLE
Como Backend necesito crear los esquemas de BBDD para probar endpoints

### ISSUE THREAD

**Issue by arbp97** [HomeBacking/Back#3]

**Comment by Dev626** [comment]
- [x] ruta a
- [x] ruta b
- [x] ruta del modulo x
- [x] ruta de la pantalla w
- [ ]

**Comment by arbp97** [comment]
Esquemas base para la BBDD terminados.
[Commit](https://github.com/HomeBacking/Back/commit/2c7716ef87cd8b2f2d0a5a422d710ed3ab24d97a)
