### ISSUE TITLE
Como backend necesito poblar data en la bbdd para utilizarla en los endpoints

### ISSUE THREAD

**Issue by Dev626** [HomeBacking/Back#4]

**Comment by arbp97** [comment]
- [x]  Usuarios

- [x]  Tarjetas 

- [x]  Cuentas

- [x]  Transacciones

- [ ]  Something else?

**Comment by arbp97** [comment]
Avance: [Commit](https://github.com/HomeBacking/Back/commit/50ae0fe1d12628f5f1cf1247fabc0339d1d401fb)

**Comment by arbp97** [comment]
Transacciones cargadas, ya estarian todos los datos base para empezar a testear
[Commit](https://github.com/HomeBacking/Back/commit/49053907638fe31c2cc11f9296cc6cf80fc54867)
