### ISSUE TITLE
Como Backend necesito crear rutas basicas de la API para que Front tenga acceso a los datos que requiera

### ISSUE THREAD

**Issue by arbp97** [HomeBacking/Back#8]
Utilizando las funciones de los modelos, para tener acceso a información básica como el balance de una cuenta o el estado de una transacción.

**Comment by arbp97** [comment]
Es necesario que Frontend enumere los endpoints que necesita. @Boniich

**Comment by Boniich** [comment]
- [x] Endpoint que contiene el monto disponible, junto con el numero y tipo de tarjeta
- [x] Endpoint transferencias
- [x] Endpoint de las demas tarjetas que contiene el mismo usuario
